# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  # Workaround for covr not putting -O0 last
  - mkdir -p ~/.R/ && echo "CFLAGS += -coverage -O0" > ~/.R/Makevars
  - Rscript -e 'covr::codecov(type = "all")'
